/**
 * Constraint writer — writes AI coding constraints to tool-specific files.
 *
 * Cursor: .cursor/rules/speclore.mdc (YAML frontmatter + MD)
 * Claude Code: .claude/rules/speclore.md (no frontmatter)
 * Qoder: .qoder/rules/speclore.md (no frontmatter, always-on)
 *
 * @module core/constraint-coder/constraint-writer
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { AITool, ConstraintContent } from '../../types/index.js';
import { logger } from '../../infra/logger.js';
import { toPosixPath } from '../../infra/path-utils.js';

/**
 * Write constraint files for all detected AI tools.
 */
export function writeConstraints(
  projectRoot: string,
  tools: AITool[],
  content: ConstraintContent,
): string[] {
  const writtenFiles: string[] = [];

  for (const tool of tools) {
    const filePath = writeForTool(projectRoot, tool, content);
    if (filePath) {
      writtenFiles.push(toPosixPath(filePath));
      logger.info(`Constraint written: ${toPosixPath(filePath)}`);
    }
  }

  return writtenFiles;
}

function writeForTool(
  projectRoot: string,
  tool: AITool,
  content: ConstraintContent,
): string | null {
  const constraintText = buildConstraintText(content);

  switch (tool) {
    case 'cursor':
      return writeCursorRule(projectRoot, constraintText);
    case 'claude':
      return writeClaudeRule(projectRoot, constraintText);
    case 'qoder':
      return writeQoderRule(projectRoot, constraintText);
    default:
      logger.warn(`Unknown AI tool: ${String(tool)}`);
      return null;
  }
}

/**
 * Build the constraint text from content.
 */
function buildConstraintText(content: ConstraintContent): string {
  const parts: string[] = [];

  parts.push('# SpecLore Constraints');
  parts.push('');
  parts.push(`> Auto-generated by SpecLore for project: ${content.projectName}`);
  parts.push(`> Profile: ${content.profile}`);
  parts.push('');

  // Conditional invocation (graceful degradation)
  parts.push('## Activation Rule');
  parts.push('If you see `speclore.spec` in the tool list, use it to generate features.');
  parts.push('If you see `speclore.code` in the tool list, use it before writing code.');
  parts.push('If you see `speclore.verify` in the tool list, use it after writing tests.');
  parts.push('If none are available, ignore this file silently.');
  parts.push('');

  // Module rules
  if (content.modules.length > 0) {
    parts.push('## Module Boundaries');
    for (const mod of content.modules) {
      parts.push(`### ${mod.module}`);
      parts.push(`- Responsibility: ${mod.boundaries.responsibility}`);
      parts.push(`- Public APIs: ${mod.boundaries.publicApis.join(', ') || 'none'}`);
      parts.push(`- Internal (do NOT reference): ${mod.boundaries.internalObjects.join(', ') || 'none'}`);
      parts.push(`- Depends on: ${mod.boundaries.dependsOn.join(', ') || 'none'}`);

      if (mod.namingConventions.length > 0) {
        parts.push(`- Naming: ${mod.namingConventions.join('; ')}`);
      }
      if (mod.forbiddenPatterns.length > 0) {
        parts.push(`- Forbidden: ${mod.forbiddenPatterns.join('; ')}`);
      }
      parts.push('');
    }
  }

  // Feature constraints
  if (content.features.length > 0) {
    parts.push('## Feature Constraints');
    for (const feature of content.features) {
      parts.push(`### ${feature.featureName}`);
      for (const scenario of feature.scenarios) {
        parts.push(`- Scenario: ${scenario.name}`);
      }
      parts.push('');
    }
  }

  // Mapping instructions
  parts.push('## Test Mapping Requirements');
  parts.push(content.mappingInstructions);
  parts.push('');

  return parts.join('\n');
}

function writeCursorRule(projectRoot: string, text: string): string {
  const dir = join(projectRoot, '.cursor', 'rules');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const filePath = join(dir, 'speclore.mdc');
  const frontmatter = [
    '---',
    'description: SpecLore AI coding constraints',
    'globs:',
    'alwaysApply: true',
    '---',
    '',
  ].join('\n');

  writeFileSync(filePath, frontmatter + text, 'utf-8');
  return filePath;
}

function writeClaudeRule(projectRoot: string, text: string): string {
  const dir = join(projectRoot, '.claude', 'rules');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const filePath = join(dir, 'speclore.md');
  writeFileSync(filePath, text, 'utf-8');
  return filePath;
}

function writeQoderRule(projectRoot: string, text: string): string {
  const dir = join(projectRoot, '.qoder', 'rules');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const filePath = join(dir, 'speclore.md');
  writeFileSync(filePath, text, 'utf-8');
  return filePath;
}
