/**
 * Built-in Claude Code writer plugin.
 * @module plugins/builtin/claude-writer
 */

import { writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import type { WriterPlugin, ConstraintContent } from '../../types/index.js';

export class ClaudeWriter implements WriterPlugin {
  readonly toolName = 'claude';
  readonly configFile = '.claude/rules/speclore.md';

  private projectRoot = '';

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.claude')) || existsSync(join(projectRoot, '.mcp.json'));
  }

  write(constraints: ConstraintContent): Promise<void> {
    this.projectRoot = constraints.projectRoot;
    const rulesDir = join(constraints.projectRoot, '.claude', 'rules');
    mkdirSync(rulesDir, { recursive: true });

    const content = this.buildMarkdown(constraints);
    writeFileSync(join(rulesDir, 'speclore.md'), content, 'utf-8');
    return Promise.resolve();
  }

  remove(): Promise<void> {
    const filePath = join(this.projectRoot, '.claude', 'rules', 'speclore.md');
    if (existsSync(filePath)) rmSync(filePath);
    return Promise.resolve();
  }

  private buildMarkdown(c: ConstraintContent): string {
    const lines: string[] = [];
    lines.push(`# SpecLore Constraints — ${c.projectName}`);
    lines.push('');
    lines.push(`> Profile: ${c.profile} | Generated by SpecLore`);
    lines.push('');

    for (const mod of c.modules) {
      lines.push(`## Module: ${mod.module}`);
      lines.push(`- **Responsibility**: ${mod.boundaries.responsibility}`);
      lines.push(`- **Depends on**: ${mod.boundaries.dependsOn.join(', ') || 'none'}`);
      if (mod.namingConventions.length > 0) {
        lines.push(`- **Naming**: ${mod.namingConventions.join('; ')}`);
      }
      if (mod.forbiddenPatterns.length > 0) {
        lines.push(`- **Forbidden**: ${mod.forbiddenPatterns.join('; ')}`);
      }
      lines.push('');
    }

    if (c.mappingInstructions) {
      lines.push('## Test Mapping');
      lines.push(c.mappingInstructions);
    }

    return lines.join('\n');
  }
}
