/**
 * Built-in Cursor writer plugin.
 * @module plugins/builtin/cursor-writer
 */

import { writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import type { WriterPlugin, ConstraintContent } from '../../types/index.js';

export class CursorWriter implements WriterPlugin {
  readonly toolName = 'cursor';
  readonly configFile = '.cursor/rules/speclore.mdc';

  private projectRoot = '';

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.cursor'));
  }

  write(constraints: ConstraintContent): Promise<void> {
    this.projectRoot = constraints.projectRoot;
    const rulesDir = join(constraints.projectRoot, '.cursor', 'rules');
    mkdirSync(rulesDir, { recursive: true });

    const frontmatter = [
      '---',
      'description: SpecLore coding constraints — auto-generated',
      'globs:',
      'alwaysApply: true',
      '---',
      '',
    ].join('\n');

    const content = frontmatter + this.buildMarkdown(constraints);
    writeFileSync(join(rulesDir, 'speclore.mdc'), content, 'utf-8');
    return Promise.resolve();
  }

  remove(): Promise<void> {
    const filePath = join(this.projectRoot, '.cursor', 'rules', 'speclore.mdc');
    if (existsSync(filePath)) rmSync(filePath);
    return Promise.resolve();
  }

  private buildMarkdown(c: ConstraintContent): string {
    const lines: string[] = [];
    lines.push(`# SpecLore Constraints — ${c.projectName}`);
    lines.push('');

    if (c.features.length > 0) {
      const featurePaths = c.features.map(f => f.path.replace(/\\/g, '/'));
      lines.push(`> Profile: ${c.profile} | Generated by SpecLore`);
      lines.push(`> Source features: ${featurePaths.join(', ')}`);
    } else {
      lines.push(`> Profile: ${c.profile} | Generated by SpecLore`);
    }
    lines.push('');

    for (const mod of c.modules) {
      lines.push(`## Module: ${mod.module}`);
      lines.push(`**Responsibility**: ${mod.boundaries.responsibility}`);
      lines.push(`**Depends on**: ${mod.boundaries.dependsOn.join(', ') || 'none'}`);
      lines.push('');
      if (mod.namingConventions.length > 0) {
        lines.push('### Naming Conventions');
        for (const n of mod.namingConventions) lines.push(`- ${n}`);
        lines.push('');
      }
      if (mod.forbiddenPatterns.length > 0) {
        lines.push('### Forbidden Patterns');
        for (const f of mod.forbiddenPatterns) lines.push(`- ${f}`);
        lines.push('');
      }
    }

    // Feature business rules
    if (c.featureRules && c.featureRules.length > 0) {
      for (const rule of c.featureRules) {
        lines.push(`## Feature Rules: ${rule.featureName}`);
        lines.push(`> Source: ${rule.sourceFile}`);
        lines.push('');
        for (const sc of rule.scenarios) {
          lines.push(`- Scenario "${sc.name}": ${sc.summary}`);
        }
        lines.push('');
      }
    }

    // Test scaffolding info
    if (c.scaffoldInfo && c.scaffoldInfo.length > 0) {
      lines.push('## Test Scaffolding');
      lines.push('Test files have been generated at:');
      for (const s of c.scaffoldInfo) {
        lines.push(`- ${s.testFile} (${s.scenarios} scenarios, ${s.framework})`);
      }
      lines.push('');
      lines.push('Fill in test implementations, then run `speclore verify` to validate.');
      lines.push('');
    }

    if (c.mappingInstructions) {
      lines.push('## Test Mapping');
      lines.push(c.mappingInstructions);
      lines.push('');
    }

    return lines.join('\n');
  }
}
