/**
 * Built-in Qoder writer plugin.
 * @module plugins/builtin/qoder-writer
 */

import { writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import type { WriterPlugin, ConstraintContent } from '../../types/index.js';

export class QoderWriter implements WriterPlugin {
  readonly toolName = 'qoder';
  readonly configFile = '.qoder/rules/speclore.md';

  private projectRoot = '';

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, '.qoder'));
  }

  write(constraints: ConstraintContent): Promise<void> {
    this.projectRoot = constraints.projectRoot;
    const rulesDir = join(constraints.projectRoot, '.qoder', 'rules');
    mkdirSync(rulesDir, { recursive: true });

    const content = this.buildMarkdown(constraints);
    writeFileSync(join(rulesDir, 'speclore.md'), content, 'utf-8');
    return Promise.resolve();
  }

  remove(): Promise<void> {
    const filePath = join(this.projectRoot, '.qoder', 'rules', 'speclore.md');
    if (existsSync(filePath)) rmSync(filePath);
    return Promise.resolve();
  }

  private buildMarkdown(c: ConstraintContent): string {
    const lines: string[] = [];
    lines.push(`# SpecLore Constraints — ${c.projectName}`);
    lines.push('');

    // Source features reference
    if (c.features.length > 0) {
      const featurePaths = c.features.map(f => {
        const rel = f.path.replace(/\\/g, '/');
        return rel;
      });
      lines.push(`> Profile: ${c.profile} | Generated by SpecLore`);
      lines.push(`> Source features: ${featurePaths.join(', ')}`);
    } else {
      lines.push(`> Profile: ${c.profile} | Generated by SpecLore`);
    }
    lines.push('');

    for (const mod of c.modules) {
      lines.push(`## Module: ${mod.module}`);
      lines.push(`- **Responsibility**: ${mod.boundaries.responsibility}`);
      lines.push(`- **Depends on**: ${mod.boundaries.dependsOn.join(', ') || 'none'}`);
      if (mod.namingConventions.length > 0) {
        lines.push(`- **Naming**: ${mod.namingConventions.join('; ')}`);
      }
      if (mod.forbiddenPatterns.length > 0) {
        lines.push(`- **Forbidden**: ${mod.forbiddenPatterns.join('; ')}`);
      }
      lines.push('');
    }

    // Feature business rules
    if (c.featureRules && c.featureRules.length > 0) {
      for (const rule of c.featureRules) {
        lines.push(`## Feature Rules: ${rule.featureName}`);
        lines.push(`> Source: ${rule.sourceFile}`);
        lines.push('');
        for (const sc of rule.scenarios) {
          lines.push(`- Scenario "${sc.name}": ${sc.summary}`);
        }
        lines.push('');
      }
    }

    // Test scaffolding info
    if (c.scaffoldInfo && c.scaffoldInfo.length > 0) {
      lines.push('## Test Scaffolding');
      lines.push('Test files have been generated at:');
      for (const s of c.scaffoldInfo) {
        lines.push(`- ${s.testFile} (${s.scenarios} scenarios, ${s.framework})`);
      }
      lines.push('');
      lines.push('Fill in test implementations, then run `speclore verify` to validate.');
      lines.push('');
    }

    if (c.mappingInstructions) {
      lines.push('## Test Mapping');
      lines.push(c.mappingInstructions);
    }

    return lines.join('\n');
  }
}
